Versioning ts code
temporalio/edu-versioning-typescript-code pull request #1
Opened 2023-11-20 16:06 UTC by angelazhou32

This is the code for the TypeScript versioning course

2023-12-01 20:35 UTC, tomwheeler requested changes

2023-12-01 20:35 UTC, tomwheeler commented on README.md
> +included in the TypeScript version of the
The URL points to the Temporal 102 course. I recommend removing the link (at least until this course is published and there's something relevant to link to) and updating the text to use the course title:

> ... included in the _Versioning Workflows with TypeScript_ training course.

2023-12-01 20:35 UTC, tomwheeler commented on README.md
> +Alternatively, you can follow
Although this link is valid, the page it points to has been updated to cover starting a development cluster with the Temporal CLI, thereby making the part of the sentence about Docker Compose invalid. Instead of pointing the learner to the docs, which cover this in a more generic way, I would just rewrite this sentence to direct them to the part of the course that explains how to run the exercises locally:

> Alternatively, you can perform these exercises directly on your computer. Refer to the instructions about setting up a local development environment, which you'll find in the "About this Course" chapter.

2023-12-01 20:35 UTC, tomwheeler commented on exercises/version-workflow/README.md
> +     `temporal workflow show \
This command is wrong. It runs successfully, but does not produce a file in JSON format. This is because it's missing a couple of the options you need. Fortunately, the command shown in the course content has them, and I used that to come up with the command to use here:

```bash
temporal workflow show \
 --workflow-id loan-processing-workflow-customer-a100 \
 --fields long \
 --output json > history_for_original_execution.json
```

2023-12-01 20:35 UTC, tomwheeler commented on exercises/version-workflow/README.md
> +4. Return to the detail page for this Workflow Execution
As with the Java version of this exercise, I found that it was not necessary to reset the Workflow Execution. 

More specifically, after deploying the change to introducing patching in step 3, the open Workflow Execution that had been experiencing the non-deterministic error eventually completed on its own. It took several minutes for that to happen (not sure how long, though, since I went downstairs to get some more water and refreshed the page when I got back to observe that the execution was then complete).

With this in mind, I would recommend eliminating steps 5 and 6 below.

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/README.md
> +During this exercise, you will
These bullet points should not end with periods

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/README.md
> +If you are running this Exercise using a local dev server, you will need to
I don't think "Exercise" requires capitalization here

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/README.md
> +To do this, run `temporal server start dev` with additional parameters:
`temporal server start dev` should be `temporal server start-dev`

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/README.md
> +temporal server start-dev \
I would **very strongly** recommend adding the`--ui-port 8080` option here so that the invocation matches what you have in the "(Optional Activity) Setting up a Local Development Environment" section in the "About this Course" chapter.

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/README.md
> +   a local dev cluster, it will be running at http://localhost:8233.
Please change the port number in this URL to 8080, after having added the `--ui-port 8080` option to the command used to start the dev server (i.e., to make the Web UI available on the same port number as it was for the rest of the course).

2023-12-01 20:35 UTC, tomwheeler commented on .gitpod.yml
> +      /workspace/bin/temporal server start-dev --db-filename your_temporal.db --ui-port 8080
This invocation of the dev server does not include the dynamic config values, and without them, the second exercise won't work in GitPod.

Please change line 24 to this, which is the invocation used in the Go version of this course:

`/workspace/bin/temporal server start-dev --dynamic-config-value frontend.workerVersioningDataAPIs=true --dynamic-config-value frontend.workerVersioningWorkflowAPIs=true --dynamic-config-value worker.buildIdScavengerEnabled=true --ui-port 8080 --db-filename $HOME/.cluster-persistence.db`

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/README.md
> +1. Run `npm start` in a terminal to start a Worker
When I ran this, I got an error:

![image](https://github.com/temporalio/edu-versioning-typescript-code/assets/2183904/fc632990-ceff-4105-bc47-4375430a1b22)

I was able to work around this by running `npm install` to install dependencies. This might not be necessary in the typical case, but was for me since I had to launch a new GitPod environment so that it would start the Temporal Cluster with the dynamic config options needed to support this exercise.

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/README.md
> +   `updateWorkerBuildIdCompatibility()` before starting your
You wrote `updateWorkerBuildIdCompatibility` here, but I don't think that's correct. The code example in the course content and what's commented out in the practice version both use`updateBuildIdCompatibility`.

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/practice/src/client.ts
> +  // await client.taskQueue.updateBuildIdCompatibility('your_task_queue_name', {
Instead of hardcoding the task queue name to a placeholder value that doesn't match what's used in this exercise, consider replacing that with `TASK_QUEUE_NAME` to use the shared constant that's already defined and being used on line 36 (it looks like the solution version is already doing that).

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/practice/src/client.ts
> +    workflowId: `pizza-workflow-order-${order.orderNumber},`,
I notice that the Workflow ID has an embedded (trailing) comma. I observed that in some of the Web UI screenshots in the course and couldn't figure out why it was there. Now I see where it came from. If it was not intentional, please remove it from the code, both here and in the solution version, (and ideally, touch up the screenshots to remove it there too; I'm happy to help you with that if needed).

![image](https://github.com/temporalio/edu-versioning-typescript-code/assets/2183904/1699492f-af1c-4a24-ab6c-59c8e9adaa5a)

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/README.md
> +   terminal window of your new Worker. This indicates that the Workflow
~I saw no such output. The last Event in the history of the new Workflow Execution was `WorkflowTaskScheduled`, which indicates that the new Worker never picked up the task.~

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/README.md
> +   terminal window of your new Worker. This indicates that the Workflow
I wasn't able to debug this, so I am giving up on GitPod and will repeat this exercise locally. Someone will still need to verify that it works correctly on GitPod before the course is released.

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/README.md
> +   terminal window of your new Worker. This indicates that the Workflow
OK, this worked fine when run locally, so I guess GitPod wasn't configured correctly.

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/README.md
> +   Version that you added in Part B. To do this, try running:
This command will almost certainly fail if someone runs it as specified, since step 1 of Part B asked the learner to choose any string they want for the build ID and the command shown here assumes that they used a specific value (namely `revision-yymmdd`).

I would recommend avoiding that by changing the sentence from this:

> To do this, try running:

to something like this:

> To do this, execute a command similar to the one below, but specify the new build ID of your choice in the `--build-id` option and replace the value of the `--existing-compatible-build-id` option with the build ID you chose earlier:

2023-12-01 20:35 UTC, tomwheeler commented on exercises/worker-versioning/practice/src/worker.ts
> +  // TODO Part B: In the object being passed into Worker.create(), add a `buildId` key and set it to a build ID string. Also add a `useVersioning` key and set it to true.
This comment is too long. It should be split across at least two or possibly three lines.

2023-12-02 15:44 UTC, angelazhou32 commented on .gitpod.yml
> +      /workspace/bin/temporal server start-dev --db-filename your_temporal.db --ui-port 8080
Thanks for the great reminder

2023-12-02 15:45 UTC, angelazhou32 commented on README.md
> +included in the TypeScript version of the
Thanks for the catch!

2023-12-02 15:53 UTC, angelazhou32 commented on exercises/version-workflow/README.md
> +     `temporal workflow show \
Thanks! Fixed

2023-12-02 15:55 UTC, angelazhou32 commented on exercises/version-workflow/README.md
> +4. Return to the detail page for this Workflow Execution
I must have missed that change! Thanks for letting me know.

2023-12-02 15:55 UTC, angelazhou32 commented on exercises/worker-versioning/README.md
> +During this exercise, you will
Fixed!

2023-12-02 15:56 UTC, angelazhou32 commented on exercises/worker-versioning/README.md
> +If you are running this Exercise using a local dev server, you will need to
fixed

2023-12-02 15:56 UTC, angelazhou32 commented on exercises/worker-versioning/README.md
> +To do this, run `temporal server start dev` with additional parameters:
fixed!

2023-12-02 15:58 UTC, angelazhou32 commented on exercises/worker-versioning/README.md
> +temporal server start-dev \
added!

2023-12-02 15:59 UTC, angelazhou32 commented on exercises/worker-versioning/README.md
> +   a local dev cluster, it will be running at http://localhost:8233.
Fixed!

2023-12-02 16:00 UTC, angelazhou32 commented on exercises/worker-versioning/practice/src/worker.ts
> +  // TODO Part B: In the object being passed into Worker.create(), add a `buildId` key and set it to a build ID string. Also add a `useVersioning` key and set it to true.
Fixed

2023-12-02 16:01 UTC, angelazhou32 commented on exercises/worker-versioning/practice/src/client.ts
> +    workflowId: `pizza-workflow-order-${order.orderNumber},`,
Great eye! removed

2023-12-02 16:20 UTC, angelazhou32 commented on exercises/worker-versioning/practice/src/client.ts
> +  // await client.taskQueue.updateBuildIdCompatibility('your_task_queue_name', {
fixed

2023-12-02 16:21 UTC, angelazhou32 commented on exercises/worker-versioning/README.md
> +   `updateWorkerBuildIdCompatibility()` before starting your
Great catch! Thanks

2023-12-02 16:22 UTC, angelazhou32 commented on exercises/worker-versioning/README.md
> +   Version that you added in Part B. To do this, try running:
thanks!

2023-12-03 15:51 UTC, angelazhou32 commented on README.md
> +Alternatively, you can follow
Changed

2023-12-11 19:16 UTC, merged